### ISSUE TITLE
If you have any problems add here.

### ISSUE THREAD

**Issue by growsenseman** [growsenseman/growsense#2]
As a developer of growsense, I would like to help you guys with errors. Thank me later :)

**Comment by heysurfer** [comment]
hi bro

**Comment by heysurfer** [comment]
![image](https://user-images.githubusercontent.com/58826689/76150057-3dc7b000-60b7-11ea-8ca8-14fa42d2b733.png)

**Comment by heysurfer** [comment]
can give metrusuit and bunifu

**Comment by growsenseman** [comment]
> can give metrusuit and bunifu

Hello, first of all thank you for asking the first question. Ok, now I will help you with the problem. As you can see, there is:
using Bunifu.Framework.UI;
using MetroSuite;
So, which means that, you have to find them from internet, add them as reference.
